modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Stack%20Refill"
logoFile="icon.png"

[[mods]]
modId="stackrefill"
version="4.4"
displayName="Stack Refill"
displayURL="https://serilum.com/mod/stack-refill"
authors="Rick South"
description='''A quality of life mod which automatically refills the item in the hand of the player when using the final item if possible.
If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.stackrefill]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.57,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stackrefill]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"