modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Stack%20Refill"
logoFile="icon.png"

[[mods]]
modId="stackrefill"
version="5.0"
displayName="Stack Refill"
displayURL="https://serilum.com/mod/stack-refill"
authors="Rick South"
description='''A quality of life mod which automatically refills the item in the hand of the player when using the final item if possible.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

akanealw, Alister, Andrean Olgo, aternosorg, Cherriesaurus, MWS, t128, Tyler Behl, XAgent, ตัวตรึง พระนคร   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.stackrefill]]
    modId="collective"
    type="required"
    versionRange="[8.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stackrefill]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.1]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "stackrefill.mixins.json"